version: "3.4"
services:
  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    volumes:
      - "./mongo-volume:/data/db"

  redis:
    image: "bitnami/redis"
    container_name: redis
    restart: always
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL

  mo2:
    image: registry.cn-hangzhou.aliyuncs.com/mo2/mo2:latest
    container_name: mo2
    restart: always
    env_file:
      - var.env
    depends_on:
      - "mongodb"
      - "redis"
      - "mo2notificationlog"
      - "mo2search"
      - "mo2imglog"
    # ports:
    #   # used for local debug
    #   - "5001:5001"
    volumes:
      - "./secrets:/app/secrets"
      - "./logs:/app/logs"
    environment:
      - COMMENT_LOG=mo2notificationlog:9990
      - IMG_LOG=mo2imglog:9990

  mo2notificationlog:
    image: registry.cn-hangzhou.aliyuncs.com/mo2/mo2log:latest
    container_name: mo2notificationlog
    restart: always
    depends_on:
      - "mongodb"
    environment:
      - MO2_MONGO_URL=mongodb://mongodb:27017
      - MO2_DATABASE=mo2
      - LOG_COL=notificationLog
      - LOG_PORT=9990

  mo2imglog:
    image: registry.cn-hangzhou.aliyuncs.com/mo2/mo2log:latest
    container_name: mo2imglog
    restart: always
    depends_on:
      - "mongodb"
    environment:
      - MO2_MONGO_URL=mongodb://mongodb:27017
      - MO2_DATABASE=mo2
      - LOG_COL=notificationLog
      - LOG_PORT=9990

  mo2search:
    image: registry.cn-hangzhou.aliyuncs.com/mo2/mo2search:latest
    container_name: mo2search
    restart: always
    volumes:
      - "./bleve:/app/.bleve"

  nginx:
    image: registry.cn-hangzhou.aliyuncs.com/mo2/nginx-le:latest
    hostname: nginx
    restart: always
    container_name: nginx

    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"

    volumes:
      - ./ssl:/etc/nginx/ssl
      - ./nginx.conf:/etc/nginx/service.conf
      # - ./etc/service-example-2.conf:/etc/nginx/service2.conf # more services, should be service*.conf
    ports:
      - "80:80"
      - "443:443"

    environment:
      - TZ=Asia/Shanghai
      - LETSENCRYPT=true
      - LE_EMAIL=chronos@motwo.cn
      - LE_FQDN=www.motwo.cn
      #- SSL_CERT=le-crt.pem
      #- SSL_KEY=le-key.pem
      #- SSL_CHAIN_CERT=le-chain-crt.pem
