apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: mo2-claim1
  name: mo2-claim1
spec:
  storageClassName: ""
  volumeName: mo2-pv1
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
