apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (955b78124)

  labels:
    io.kompose.service: mo2
  name: mo2
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mo2
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.22.0 (955b78124)

      labels:
        io.kompose.service: mo2
    spec:
      priorityClassName: high-priority
      containers:
        - env:
            - name: COMMENT_LOG
              value: mo2notificationlog:9990
            - name: GITHUB_ID
              valueFrom:
                secretKeyRef:
                  key: GITHUB_ID
                  name: var-env
            - name: GITHUB_SECRET
              valueFrom:
                secretKeyRef:
                  key: GITHUB_SECRET
                  name: var-env
            - name: IMG_LOG
              value: mo2imglog:9990
            - name: MO2_SEARCH_HOST
              valueFrom:
                configMapKeyRef:
                  key: MO2_SEARCH_HOST
                  name: var-env
            - name: MO2_SUPER_KEY
              valueFrom:
                secretKeyRef:
                  key: MO2_SUPER_KEY
                  name: var-env
            - name: emailAddr
              valueFrom:
                secretKeyRef:
                  key: emailAddr
                  name: var-env
            - name: emailPass
              valueFrom:
                secretKeyRef:
                  key: emailPass
                  name: var-env
            - name: qiniuak
              valueFrom:
                secretKeyRef:
                  key: qiniuak
                  name: var-env
            - name: qiniusk
              valueFrom:
                secretKeyRef:
                  key: qiniusk
                  name: var-env
          image: registry.cn-hangzhou.aliyuncs.com/mo2/mo2:latest
          resources:
            limits:
              cpu: 300m
              memory: 100Mi
            requests: 
              cpu: 200m
              memory: 50Mi
          name: mo2
          ports:
            - containerPort: 5001
      
      initContainers:
      - name: init-mongodb
        image: busybox
        command: ['sh', '-c', "until nslookup mongodb.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for mongodb; sleep 2; done"]
      restartPolicy: Always
status: {}
---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: mo2
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: mo2
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 60