apiVersion: v1
kind: PersistentVolume
metadata:
  name: mo2-pv1
  labels:
    type: local
spec:
  storageClassName: ""
  # claimRef:
  #   name: mo2-claim1
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/mo2/mo2/logs"