apiVersion: v1
kind: PersistentVolume
metadata:
  name: mo2search-pv
  labels:
    type: local
spec:
  storageClassName: ""
  # claimRef:
  #   name: mo2search-claim0
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  nfs:
    server: 172.22.174.157
    path: "/mnt/mo2/mo2search"
