apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: mo2search-claim0
  name: mo2search-claim0
spec:
  storageClassName: ""
  volumeName: mo2search-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
