apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (955b78124)

  labels:
    io.kompose.service: nginx
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: nginx
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.22.0 (955b78124)

      labels:
        io.kompose.service: nginx
    spec:
      priorityClassName: high-priority
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      nodeName: backend-server-1
      containers:
        - env:
            - name: LETSENCRYPT
              value: "true"
            - name: LE_EMAIL
              valueFrom:
                configMapKeyRef:
                  key: LE_EMAIL
                  name: var-env
            - name: LE_FQDN
              valueFrom:
                configMapKeyRef:
                  key: LE_FQDN
                  name: var-env
            - name: TZ
              value: Asia/Shanghai
          image: registry.cn-hangzhou.aliyuncs.com/mo2/nginx-le:latest
          name: nginx
          ports:
            - name: "p80"
              containerPort: 80
            - name: "p443"
              containerPort: 443
          resources:
            limits:
              cpu: 1000m
              memory: 200Mi
            requests: 
              cpu: 200m
              memory: 200Mi
          volumeMounts:
            - mountPath: /etc/nginx/ssl
              name: nginx-claim0
      hostname: nginx
      restartPolicy: Always
      volumes:
        - name: nginx-claim0
          persistentVolumeClaim:
            claimName: nginx-claim0
status: {}
