apiVersion: v1
kind: PersistentVolume
metadata:
  name: nginx-pv1
  labels:
    type: local
spec:
  storageClassName: ""
  # claimRef:
  #   name: nginx-claim1
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  local:
    path: "/mnt/mo2/nginx/service.conf"
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - izwz9iyowiok93f5x0h8faz