apiVersion: v1
kind: PersistentVolume
metadata:
  name: nginx-pv0
  labels:
    type: local
spec:
  storageClassName: ""
  # claimRef:
  #   name: nginx-claim0
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  nfs:
    server: 172.22.174.157
    path: "/mnt/mo2/nginx/ssl"
